// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DIRECT_URL for migrations, DATABASE_URL for runtime
    url: process.env["DIRECT_URL"],
  },
  // For Prisma Client, we'll use DATABASE_URL (pooler)
  generator: {
    // This is handled in the schema file
  },
});
